package io.github.mi8qa.restassured.context;

import java.time.LocalDateTime;
import java.util.concurrent.Callable;

/**
 * Enumeration representing custom request headers.
 * Each enum constant is associated with a Callable that generates its value.
 * <p>
 * This enum includes a custom request time header, which generates its value based on the current local date and time.
 *
 * @since [Date or Version]
 */
public enum CustomRequestHeaders {

	/**
	 * Custom request time header.
	 * Its value is generated based on the current local date and time.
	 */
	CUSTOM_REQUEST_TIME(() -> LocalDateTime.now().toString());

	// The Callable responsible for generating the value of the custom header.
	private final Callable<String> valueGenerator;

	/**
	 * Constructs a new CustomRequestHeaders enum constant.
	 *
	 * @param valueGenerator The Callable responsible for generating the value of the custom header.
	 */
	CustomRequestHeaders(Callable<String> valueGenerator) {
		this.valueGenerator = valueGenerator;
	}

	/**
	 * Retrieves the value generated by the associated Callable.
	 *
	 * @return The generated value, or "failedToGenerateValue" if an exception occurs.
	 */
	public String value() {
		try {
			return valueGenerator.call();
		} catch (Exception e) {
			return "failedToGenerateValue";
		}
	}
}
